---
# tasks/main.yml

- name: Ensure /etc/profile contains the Ansible block
  lineinfile:
    path: /etc/profile
    line: "#Test block added by Ansible……n01649144"
    insertafter: EOF

- name: Set TMOUT in /etc/profile
  lineinfile:
    path: /etc/profile
    line: "export TMOUT=1500"
    insertafter: "#Test block added by Ansible……n01649144"
