---
# tasks/main.yml

- name: Create cloudadmins group
  group:
    name: cloudadmins
    state: present

- name: Create user accounts
  user:
    name: "{{ item }}"
    groups: cloudadmins,wheel
    state: present
    generate_ssh_key: yes
    ssh_key_file: /home/{{ item }}/.ssh/id_rsa
  loop:
    - user100
    - user200
    - user300

- name: Ensure proper permissions for SSH directory
  file:
    path: /home/{{ item }}/.ssh
    state: directory
    mode: '0700'
    owner: "{{ item }}"
    group: "{{ item }}"
  loop:
    - user100
    - user200
    - user300

- name: Ensure proper permissions for SSH private key
  file:
    path: /home/{{ item }}/.ssh/id_rsa
    state: file
    mode: '0600'
    owner: "{{ item }}"
    group: "{{ item }}"
  loop:
    - user100
    - user200
    - user300

- name: Ensure proper permissions for SSH public key
  file:
    path: /home/{{ item }}/.ssh/id_rsa.pub
    state: file
    mode: '0644'
    owner: "{{ item }}"
    group: "{{ item }}"
  loop:
    - user100
    - user200
    - user300

- name: Download private key for user100 to local machine
  fetch:
    src: /home/user100/.ssh/id_rsa
    dest: ./user100_id_rsa
    flat: yes
